<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="7" name="pytest" skips="0" tests="8" time="0.493"><testcase classname="pytests.test_index" file="pytests/test_index.py" line="10" name="test_conda_environment_activated" time="0.0016694068908691406"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="13" name="test_restaurant_name_func" time="0.0026535987854003906"><failure message="AssertionError: assert None == &apos;Fork &amp; Fig&apos;
 +  where None = restaurant_name({&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...})">def test_restaurant_name_func():
        assert &apos;restaurant_name&apos; in ipynb.fs.full.index.__dict__, &quot;The restaurant_name function must be defined&quot;
&gt;       assert restaurant_name(fork_fig) == &apos;Fork &amp; Fig&apos;
E       AssertionError: assert None == &apos;Fork &amp; Fig&apos;
E        +  where None = restaurant_name({&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...})

pytests/test_index.py:16: AssertionError</failure></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="18" name="test_restaurant_rating_func" time="0.0012230873107910156"><failure message="AssertionError: assert None == 4.5
 +  where None = restaurant_rating({&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...})">def test_restaurant_rating_func():
        assert &apos;restaurant_rating&apos; in ipynb.fs.full.index.__dict__, &quot;The restaurant_rating function must be defined&quot;
&gt;       assert restaurant_rating(fork_fig) == 4.5
E       AssertionError: assert None == 4.5
E        +  where None = restaurant_rating({&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...})

pytests/test_index.py:21: AssertionError</failure></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="23" name="test_is_better_func" time="0.0013751983642578125"><failure message="AssertionError: assert None == False
 +  where None = is_better({&apos;categories&apos;: [{&apos;alias&apos;: &apos;mexican&apos;, &apos;title&apos;: &apos;Mexican&apos;}, {&apos;alias&apos;: &apos;diners&apos;, &apos;title&apos;: &apos;Diners&apos;}, {&apos;alias&apos;: &apos;tradameri...0808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}, {&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...})">def test_is_better_func():
        assert &apos;is_better&apos; in ipynb.fs.full.index.__dict__, &quot;The is_better function must be defined&quot;
&gt;       assert is_better(frontier_restaurant, fork_fig) == False
E       AssertionError: assert None == False
E        +  where None = is_better({&apos;categories&apos;: [{&apos;alias&apos;: &apos;mexican&apos;, &apos;title&apos;: &apos;Mexican&apos;}, {&apos;alias&apos;: &apos;diners&apos;, &apos;title&apos;: &apos;Diners&apos;}, {&apos;alias&apos;: &apos;tradameri...0808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}, {&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...})

pytests/test_index.py:26: AssertionError</failure></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="29" name="test_is_cheaper_func" time="0.001146078109741211"><failure message="AssertionError: assert None == True
 +  where None = is_cheaper({&apos;categories&apos;: [{&apos;alias&apos;: &apos;mexican&apos;, &apos;title&apos;: &apos;Mexican&apos;}, {&apos;alias&apos;: &apos;diners&apos;, &apos;title&apos;: &apos;Diners&apos;}, {&apos;alias&apos;: &apos;tradameri...0808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}, {&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...})">def test_is_cheaper_func():
        assert &apos;is_cheaper&apos; in ipynb.fs.full.index.__dict__, &quot;The is_cheaper function must be defined&quot;
&gt;       assert is_cheaper(frontier_restaurant, fork_fig) == True
E       AssertionError: assert None == True
E        +  where None = is_cheaper({&apos;categories&apos;: [{&apos;alias&apos;: &apos;mexican&apos;, &apos;title&apos;: &apos;Mexican&apos;}, {&apos;alias&apos;: &apos;diners&apos;, &apos;title&apos;: &apos;Diners&apos;}, {&apos;alias&apos;: &apos;tradameri...0808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}, {&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...})

pytests/test_index.py:32: AssertionError</failure></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="35" name="test_high_rating_func" time="0.001116037368774414"><failure message="AssertionError: assert None == True
 +  where None = high_rating({&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...}, 4)">def test_high_rating_func():
        assert &apos;high_rating&apos; in ipynb.fs.full.index.__dict__, &quot;The high_rating function must be defined&quot;
&gt;       assert high_rating(fork_fig, 4) == True
E       AssertionError: assert None == True
E        +  where None = high_rating({&apos;categories&apos;: [{&apos;alias&apos;: &apos;burgers&apos;, &apos;title&apos;: &apos;Burgers&apos;}, {&apos;alias&apos;: &apos;sandwiches&apos;, &apos;title&apos;: &apos;Sandwiches&apos;}, {&apos;alias&apos;: &apos;s...{&apos;latitude&apos;: 35.10871, &apos;longitude&apos;: -106.56739}, &apos;display_phone&apos;: &apos;(505) 881-5293&apos;, &apos;distance&apos;: 3571.724649307866, ...}, 4)

pytests/test_index.py:38: AssertionError</failure></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="41" name="test_mean_review_count_func" time="0.0013971328735351562"><failure message="AssertionError: assert None == 1261.0
 +  where None = mean_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])">def test_mean_review_count_func():
        assert &apos;mean_review_count&apos; in ipynb.fs.full.index.__dict__, &quot;The mean_review_count function must be defined&quot;
&gt;       assert mean_review_count(restaurant_list) == 1261.0
E       AssertionError: assert None == 1261.0
E        +  where None = mean_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])

pytests/test_index.py:44: AssertionError</failure></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="45" name="test_mediam_review_count_func" time="0.001371622085571289"><failure message="AssertionError: assert None == 1284.5
 +  where None = median_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])">def test_mediam_review_count_func():
        assert &apos;median_review_count&apos; in ipynb.fs.full.index.__dict__, &quot;The median_review_count function must be defined&quot;
&gt;       assert median_review_count(restaurant_list) == 1284.5
E       AssertionError: assert None == 1284.5
E        +  where None = median_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])

pytests/test_index.py:48: AssertionError</failure></testcase></testsuite>